### ISSUE TITLE
Úkol 1

### ISSUE THREAD

**Issue by adelakrejbychova** [adelakrejbychova/python-2022#1]
https://github.com/adelakrejbychova/python-2022/blob/main/baliky.py
Ahoj, odevzdávám úkol č. 1. :)

Adéla K.

**Comment by M-Kovar** [comment]
Ahoj Adélo, propojili jsme se a úkol vidím v repozitáři a odevzdaný formou issue, takže nám všechno funguje:).

K úkolu: Skvělá práce, kód funguje a dokonce jsi ho rovnou vylepšila o balíky mimo "databázi", takže dvojnásobná pochvala:). Mám k tomu jedno upřesnění:

* Jak nedávno vysvětlila i Andy na Slacku (channel "ukol_1"), psát v podmínce `== True` nebo `== False` není potřeba a v praxi se obvykle nepíše. Už samotné `baliky[kod_baliku]` totiž vrací True nebo False. Takže třeba v případě předaného balíku by ve Tvé variantě vzniklo `if True == True`, což se stejně vyhodnotí na `True`. V případě nepředaného balíku by bylo `if False == True`, z čehož zase vznikne `False`. Podmínku je tedy dobré napsat pouze jako `if baliky[kod_baliku]`. ...Pro porovnání, první podmínka by vlastně taky šla napsat jako `if kod_baliku in baliky == True`, ale to True by tam bylo nadbytečné, protože už samotné `kod_baliku in baliky` vrací True nebo False potřebné pro rozhodnutí podmínky.

Pro zajímavost, v podobných podmínkách založených na proměnné obsahující True/False se často používají názvy jako is_valid, is_number, package_delivered, či podobné návodné názvy, aby se kód snadno četl. V našem případě bychom si třeba mohli "hodnotu" balíku uložit jako `balik_predan = baliky[kod_baliku]` a potom mít podmínku `if balik_predan`, což je pro programátora snadno pochopitelné, protože to zní skoro jako běžná věta. (Na druhou stranu, v našem příkladu by asi bylo zbytečné vytvářet další proměnnou, jelikož je kód snadno pochopitelný i bez ní - záleží tedy spíš na vlastním pocitu, co je Ti bližší a jak si to chceš napsat:).)

Díky za odevzdání a na viděnou v úterý:).
