### ISSUE TITLE
Úkol 2

### ISSUE THREAD

**Issue by adelakrejbychova** [adelakrejbychova/python-2022#2]
https://github.com/adelakrejbychova/python-2022/blob/main/ukol2.py

Čauky, odevzdávám úkol číslo 2. Snad z toho poznáš mé mozkové pochody, snažila jsem se aspoň trochu okomentovat. 
Řešení začíná od řádku 492... :) 

Díky za kontrolu, Adéla

**Comment by M-Kovar** [comment]
Ahoj Adélo, mozkové pochody máš výborné, funguje to, jak má - dobrá práce a chválím okomentování kódu. Celkově moc pěkné a promyšlené:). Co mě napadlo:
- Počítadlo `pocet_statu` jde s klidem nahradit `pocet_statu = len(staty)`. Máme to hned a ušetříme dva řádky kódu:).
- V ifu místo `novy_slovnik.keys()` stačí `novy_slovnik`, jelikož se python i tak dívá jen na klíče.
- Tohle je fakt jen drobnost pro estetiku: proměnné `novy_subregion` a `nova_population` snad ani není třeba zakládat (použijí se jen jednou) a místo toho napsat rovnou třeba `novy_slovnik[stat['subregion']] = stat['population']` . Ale pokud Ti to pomáhá se v kódu líp vyznat, klidně si proměnné zakládej - v některých situacích je i to lepší. Nebo si naopak můžeš `novy_subregion` založit ještě před ifem a pak ho používat místo `stat['subregion']`.

Pro zajímavost, neznámý region by šel řešit mírně úsporněji ještě třeba takto:
```
zadani = input("Zadej region: ")
staty_v_regionu = []
for stat in staty:
    if zadani == stat["region"]:
        staty_v_regionu.append(stat)
        print(stat["name"])
if not staty_v_regionu:
    print("Neznámý region")
```
... Projíždím slovník a do seznamu si sbírám státy ze zvoleného regionu. V případě neznámého regionu se mi nic neprintuje a seznam zůstane prázdný. Ifem pak kouknu, jestli je seznam prázdný - pokud ano, znamená to neznámý region. A případně pak posbírané státy můžu rovnou využít i pro bonusový úkol:).
